[CloudMinds] 10355-General Info
OpenMobileAlliance/lwm2m-registry pull request #310
Opened 2019-11-06 02:56 UTC by Kenny-SZ

This LWM2M Object contains the referrence to all general info objects.

2019-11-26 09:23 UTC, akeranen requested changes

2019-11-26 09:23 UTC, akeranen commented on 10355.xml
> +    <Name>General Info</Name>
This is too generic name for such specific object. Better e.g., "Robot Info"?

2019-11-26 09:23 UTC, akeranen commented on 10355.xml
> +		<Name>Robot General Info</Name>
Name doesn't seem to match the purpose of the resource

2019-11-26 09:23 UTC, akeranen commented on 10355.xml
> +		  <![CDATA[Contains the reference to the RCU of the Robot.]]>
Please expand the acronyms here and in all other places in the model descriptions; for short acronyms consider expanding also in names.

2019-11-26 09:23 UTC, akeranen commented on 10355.xml
> +    <Description1><![CDATA[This LWM2M Object contains the referrence to all general info objects.]]></Description1>
..of robots

2019-12-03 01:29 UTC, Kenny-SZ commented on 10355.xml
> +    <Description1><![CDATA[This LWM2M Object contains the referrence to all general info objects.]]></Description1>
Thanks for your comments, updated.

2020-01-09 15:31 UTC, merged