[ADMIN-Editorial] Bug fixes for dmse objects
OpenMobileAlliance/lwm2m-registry pull request #473
Opened 2020-06-04 03:13 UTC by jpradocueva

I have created a new PR with the changes that are needed in the DMSE objects to resolve the current validation issues: https://github.com/OpenMobileAlliance/objects-lwm2m/issues/95

Before merging this PR the corresponding CRs need to be created against the affected Enablers and presented to DMSE not later than June 16th; approval date.
I am assuming that the TS is not updated. If this is not the case, then Objects and DDF.xml MAY need an upate.

2020-06-04 11:38 UTC, seanmcilroy29 commented on DDF.xml
>          <TS>http://www.openmobilealliance.org/release/LWM2M_LOCKWIPE/V1_0_1-20181003-A/OMA-TS-LWM2M_LockWipe-V1_0-20180615-A.pdf</TS>
LOCKWIPE TS will require updating to incorporate the changes to v1_0_1 - Did you want to update the links in this PR?

2020-06-04 11:40 UTC, seanmcilroy29 commented on DDF.xml
>          <TS>http://www.openmobilealliance.org/release/LWM2M_SWMGMT/V1_0-20180301-A/OMA-TS-LWM2M_SwMgmt-V1_0-20180301-A.pdf</TS>
SwMgmt TS will require updating to incorporate the changes to v1_0_1 - Did you want to update the links in this PR?

2020-06-04 11:46 UTC, seanmcilroy29 commented
@jpradocueva - All the associated TS links in these Objects will require updating, did you want to apply the updates to this PR or in another?

2020-06-09 10:19 UTC, jmudge requested changes
- The Legal Disclaimers need to be updated e.g. in LWM2M_DevCapMgmt-v1_0_1.xml & LWM2M_Portfolio-v1_0_1.xml .
- LWM2M_DevCapMgmt-v1_0_1.xml it is suggested that line 103 is updated to "9..15: reserved"

2020-06-17 04:01 UTC, jpradocueva commented
@seanmcilroy29 @jmudge we will have to keep this PR here until the new TS's are published. At the moment the validator detects that the TS are not available.

2020-06-23 06:53 UTC, seanmcilroy29 commented
@jpradocueva - bug-fix branch now validates with no errors

2020-06-23 14:14 UTC, jmudge approved these changes

2020-06-23 16:13 UTC, merged