[ADMIN] Publication March 2024 Final Approval
OpenMobileAlliance/lwm2m-registry pull request #753
Opened 2024-04-15 12:42 UTC by gocadimic

> Note:

**In making a submission to the Open Mobile Alliance Registry, you understand and agree that your submission is made under the BSD-3 Clause License as set forth on the Open Mobile Alliance Registry and that additional formats of your submission may be created by the Open Mobile Alliance tools and processes, which may convert the content of your submission, and that the Open Mobile Alliance bears no liability for the additional formats of your submission nor for any conversion of the content of your submission.**

2024-04-24 14:20 UTC, jpradocueva approved these changes
Ok

2024-05-06 00:30 UTC, jpradocueva commented on DDF.xml
> +        <URN>urn:oma:lwm2m:oma:8:1.0</URN>
```suggestion
        <URN>urn:oma:lwm2m:oma:8</URN>
```

2024-05-06 00:30 UTC, jpradocueva commented on DDF.xml
> +        <URN>urn:oma:lwm2m:oma:8:1.0</URN>
The first version, v1.0, doesn't need to be added to the URN.

2024-05-06 00:33 UTC, jpradocueva approved these changes
FIrst object version `v1.0`, doesn't need to be added to the URN naming.

2024-05-06 00:33 UTC, jpradocueva commented on DDF.xml
> +        <URN>urn:oma:lwm2m:oma:9:1.0</URN>
```suggestion
        <URN>urn:oma:lwm2m:oma:9</URN>
```

2024-05-06 00:33 UTC, jpradocueva commented on DDF.xml
> +        <URN>urn:oma:lwm2m:oma:14:1.0</URN>
```suggestion
        <URN>urn:oma:lwm2m:oma:14</URN>
```

2024-05-06 00:33 UTC, jpradocueva commented on DDF.xml
> +        <URN>urn:oma:lwm2m:oma:15:1.0</URN>
```suggestion
        <URN>urn:oma:lwm2m:oma:15</URN>
```

2024-05-06 00:33 UTC, jpradocueva commented on DDF.xml
> +        <URN>urn:oma:lwm2m:oma:19:1.0</URN>
```suggestion
        <URN>urn:oma:lwm2m:oma:19</URN>
```

2024-05-06 00:33 UTC, jpradocueva commented on DDF.xml
> +        <URN>urn:oma:lwm2m:oma:25:1.0</URN>
```suggestion
        <URN>urn:oma:lwm2m:oma:25</URN>
```

2024-05-06 14:10 UTC, jpradocueva requested changes
One comment left behind about the pointer to the TS for Dev Capabilities.

2024-05-06 14:10 UTC, jpradocueva commented on DDF.xml
> +        <TS>https://www.openmobilealliance.org/release/LWM2M_DevCapMgmt/V2_0_1-20240312-A/OMA-SUP-XML_15-V2_0_1-20240212-A.xml</TS>
@gocadimic, this link must point to the TS, not the Object. You need to update the link to point to https://www.openmobilealliance.org/release/LWM2M_DevCapMgmt/V2_0_1-20240312-A/OMA-TS-LWM2M_DevCapMgmt-V2_0_1-20240312-A.pdf

2024-05-06 21:19 UTC, gocadimic commented on DDF.xml
> +        <TS>https://www.openmobilealliance.org/release/LWM2M_DevCapMgmt/V2_0_1-20240312-A/OMA-SUP-XML_15-V2_0_1-20240212-A.xml</TS>
@jpradocueva, The link has been updated to point to TS.

2024-05-07 19:22 UTC, merged